name: Scrape Vaughn Live

on:
  # 1. Dispara al hacer push sobre main, para poder probar inmediatamente
  push:
    branches:
      - main                           # :contentReference[oaicite:0]{index=0}

  # 2. Dispara cada 4 horas en UTC
  schedule:
    - cron: '0 */4 * * *'             # :contentReference[oaicite:1]{index=1}

  # 3. Habilita ejecución manual desde la interfaz (Run workflow)
  workflow_dispatch:                 # :contentReference[oaicite:2]{index=2}

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instala Playwright y navegadores
        run: |
          pip install --upgrade pip
          pip install playwright
          playwright install --with-deps

      - name: Ejecuta tu scraper
        run: python main.py

      - name: Sube canales.json como artifact
        uses: actions/upload-artifact@v4
        with:
          name: canales-json
          path: canales.json
