name: Scrape Vaughn Live

on:
  schedule:
    - cron: '0 */4 * * *'     # Cada 4 horas (UTC)
  workflow_dispatch:         # Habilita ejecución manual :contentReference[oaicite:0]{index=0}

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instala Playwright y navegadores
        run: |
          pip install --upgrade pip
          pip install playwright
          playwright install --with-deps

      - name: Ejecuta tu scraper
        run: python main.py

      - name: Sube canales.json como artifact
        uses: actions/upload-artifact@v4
        with:
          name: canales-json
          path: canales.json

