name: Scrape Vaughn Live

# ─── Eleva aquí los permisos del GITHUB_TOKEN ─────────────────────────
permissions:
  contents: write    # Habilita push sobre el repo :contentReference[oaicite:7]{index=7}

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with: { python-version: '3.11' }

      - name: Install Playwright & browsers
        run: |
          pip install --upgrade pip
          pip install playwright
          playwright install --with-deps

      - name: Run scraper
        run: python main.py

      - name: Upload canales.json artifact
        uses: actions/upload-artifact@v4
        with:
          name: canales-json
          path: canales.json

      - name: Commit and push canales.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update canales.json via GitHub Actions"
          file_pattern: "canales.json"
          branch: main
          push_options: --force-with-lease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
