name: Scrape Vaughn Live

on:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install --with-deps

      - run: python main.py

      - uses: actions/upload-artifact@v4
        with:
          name: canales-json
          path: canales.json
